In [ ]:

#Para identificar plagio de ChatGPT, puedes seguir los siguientes pasos:
#Recopilar un conjunto de textos originales de ChatGPT y otro conjunto de textos sospechosos de ser plagio.
#Preprocesar los textos para eliminar las palabras vacías, puntuaciones y caracteres especiales.
#Crear una matriz de términos de documentos (DTM) a partir de los textos procesados. Esto implica contar la frecuencia de cada palabra en cada texto y representar los datos en una matriz.
#Dividir los datos en conjuntos de entrenamiento y prueba.
#Entrenar un modelo de clasificación, como un clasificador binario o un clasificador de varias clases, utilizando el conjunto de entrenamiento. Puedes usar diferentes algoritmos de aprendizaje automático, como SVM, Naive Bayes, Redes Neuronales, etc.
#Evaluar el modelo utilizando el conjunto de prueba y medir la precisión, la sensibilidad y la especificidad.
#Una vez que el modelo esté entrenado, puedes usarlo para identificar plagio de ChatGPT en textos nuevos.
#Si un texto es etiquetado como plagio, se puede realizar una inspección manual para confirmar el plagio.
#Si se confirma el plagio, se puede tomar medidas apropiadas para informar a las partes involucradas y tomar medidas disciplinarias si es necesario.
#En resumen, el algoritmo implicaría recopilar y preprocesar los datos, crear una matriz de términos de documentos, entrenar un modelo de clasificación y usarlo para identificar el plagio de ChatGPT.

In [57]:
import os
import csv
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string
import pandas as pd
import numpy as np
import pickle
import re

In [58]:
csvCHATGPT = pd.read_csv("TextosCHATGPT2.csv")

In [59]:
csvCHATGPT

Textos
0  Los perros son animales domésticos populares e...
1  Los perros son animales fascinantes que han fo...
2  Los perros son animales increíbles que han est...
3  Los perros son mamíferos que pertenecen a la f...
4  Los perros son animales extraordinarios que ha...

In [60]:
csvCHATGPT.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Textos  5 non-null      object
dtypes: object(1)
memory usage: 168.0+ bytes


In [61]:
texto_columna = csvCHATGPT['Textos']

In [62]:
texto_limpio = texto_columna.str.replace('[^\w\s]','')

C:\Users\ivaan\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.


In [63]:
texto_limpio = texto_limpio.str.lower()

In [64]:
texto_limpio = texto_limpio.str.strip()

In [65]:
csvCHATGPT['Textos'] = texto_limpio

In [66]:
csvCHATGPT

Textos
0  los perros son animales domésticos populares e...
1  los perros son animales fascinantes que han fo...
2  los perros son animales increíbles que han est...
3  los perros son mamíferos que pertenecen a la f...
4  los perros son animales extraordinarios que ha...

In [67]:
csvCHATGPT.to_csv('csvCHATGPT_limpios.csv', index=False)

In [70]:
import csv
import nltk
nltk.download('punkt')
import pandas as pd
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords


textos = []
with open('csvCHATGPT_limpios.csv', newline='', encoding='utf-8') as csvfile:
    reader = csv.reader(csvfile)
    for row in reader:
        textos.append(row[0])
        tokenizados = []

for texto in textos:
    tokens = nltk.word_tokenize(texto)
    tokenizados.append(tokens)

with open('csvCHATGPT_tokenizado.csv', mode='w', newline='', encoding='utf-8') as csvfile:
    writer = csv.writer(csvfile)
    for tokens in tokenizados:
        writer.writerow(tokens)

#stop_words = set(stopwords.words("es"))
#Stop words
#for texto in textos:
#    texto = [word for word in texto if not word in nltk.corpus.stopwords.words('spanish')]
    


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ivaan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ivaan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [69]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# leer el archivo CSV en un DataFrame de Pandas
dframe = pd.read_csv('csvCHATGPT_limpios.csv')

# preprocesamiento de datos: convertir texto a minúsculas y eliminar signos de puntuación
#df['texto'] = df['texto'].str.lower().str.replace('[^\w\s]', '')

# crear la matriz de términos de documentos
vectorizer = CountVectorizer()
td_matrix = vectorizer.fit_transform(dframe['Textos'])

# obtener la lista de términos (palabras)
terms = vectorizer.get_feature_names()

# imprimir la matriz de términos de documentos
print(td_matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [1 1 0 ... 1 1 1]
 [0 0 0 ... 0 0 1]]


c:\Users\ivaan\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [73]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier


# Cargar datos desde un archivo CSV
textos = []
with open('csvCHATGPT_limpios.csv', newline='', encoding='utf-8') as csvfile:
    reader = csv.reader(csvfile)
    for row in reader:
        textos.append(row[0])

# Abrir el archivo en modo lectura
archivo = open('ejemplo.txt', 'r')
# Leer el contenido del archivo y almacenarlo en una variable
contenidotxt = archivo.read()
# Imprimir el contenido
#print(contenidotxt)

# Crear un DataFrame para almacenar los datos
df = pd.DataFrame({"text": textos, "plagio": [0]*len(textos)})
df.loc[len(df)] = [contenidotxt, -1]

# Separar los datos en conjunto de entrenamiento y prueba
#train_data, test_data, train_labels, test_labels = train_test_split(df['plagio'], test_size=0.2, random_state=42)

# Vectorizar los datos de texto
vectorizer = TfidfVectorizer()
train_vectors = vectorizer.fit_transform(df["text"])
#test_vectors = vectorizer.transform(test_data)

# Entrenar un modelo SVM
#model = SVC(kernel='linear')
#model.fit(train_vectors, train_labels)
# Entrenar el modelo de Random Forest

# Dividir los datos en conjunto de entrenamiento y conjunto de prueba
X_train, X_test, y_train, y_test = train_test_split(train_vectors, df["plagio"], test_size=0.2, random_state=42)

# Entrenar el modelo de Random Forest
modelo = RandomForestClassifier(n_estimators=100)
modelo.fit(X_train, y_train)

# Predecir las etiquetas de los datos de prueba
#predicted_labels = modelo.predict(test_vectors)

# Calcular la precisión del modelo
#accuracy = accuracy_score(test_labels, predicted_labels)
#print('Precisión del modelo: {:.2f}'.format(accuracy))

# Evaluar la precisión del modelo en el conjunto de entrenamiento y el conjunto de prueba
y_train_pred = modelo.predict(X_train)
y_test_pred = modelo.predict(X_test)
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)
print("Precisión en el conjunto de entrenamiento:", train_accuracy)
print("Precisión en el conjunto de prueba:", test_accuracy)

# Predecir la probabilidad de plagio del PDF a comparar
prob_plagio = modelo.predict_proba(X_test)[-1][-1]

# Calcular el porcentaje de plagio
porcentaje_plagio = round(prob_plagio * 100, 2)

# Imprimir el porcentaje de plagio
print("Porcentaje de plagio:", porcentaje_plagio, "%")

Precisión en el conjunto de entrenamiento: 1.0
Precisión en el conjunto de prueba: 0.5
Porcentaje de plagio: 81.0 %
